Plug 'Shougo/denite.nvim'
Plug 'pocari/vim-denite-emoji'
Plug 'junegunn/vim-emoji'
Plug 'bfredl/nvim-miniyank'
Plug 'iyuuya/denite-ale'
Plug 'chemzqm/denite-git'
Plug 'iamcco/react-error-codes.vim'
Plug 'iamcco/buzuo.vim'
Plug 'iamcco/project.vim'
Plug 'iamcco/denite-source.vim'
Plug 'iamcco/gitignore.vim'
Plug 'iamcco/universal-editorconfig'
Plug 'iamcco/coc-action-source.nvim'
Plug 'iamcco/devdocs.nvim', { 'do': 'npm install' }
Plug 'iamcco/lxiym.vim'
