Plug 'chemzqm/vim-jsx-improve'
Plug 'chemzqm/jsonc.vim'
Plug 'leafgarland/typescript-vim'
Plug 'iamcco/dart-vim-plugin'
Plug 'posva/vim-vue'
Plug 'dag/vim-fish'
Plug 'iamcco/vim-stylus'
Plug 'tpope/vim-markdown'
